version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: itmcuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: timeclock
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
